export {default as AboutUs} from "./AboutUs"
export {default as ContactUs} from "./ContactUs"
export {default as Products} from "./Products"
export {default as Home} from "./Home"
export {default as KidsSection} from "./Kids"
export {default as MensSection} from "./Mens"
export {default as WomensSection} from "./Womens"
export {default as SaleSection}  from "./Sale"
export {default as Brands} from "./Brandss"

